<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Display Debug backtrace
|--------------------------------------------------------------------------
|
| If set to TRUE, a backtrace will be displayed along with php errors. If
| error_reporting is disabled, the backtrace will not display, regardless
| of this setting
|
*/
defined('SHOW_DEBUG_BACKTRACE') OR define('SHOW_DEBUG_BACKTRACE', TRUE);

/*
|--------------------------------------------------------------------------
| File and Directory Modes
|--------------------------------------------------------------------------
|
| These prefs are used when checking and setting modes when working
| with the file system.  The defaults are fine on servers with proper
| security, but you may wish (or even need) to change the values in
| certain environments (Apache running a separate process for each
| user, PHP under CGI with Apache suEXEC, etc.).  Octal values should
| always be used to set the mode correctly.
|
*/
defined('FILE_READ_MODE')  OR define('FILE_READ_MODE', 0644);
defined('FILE_WRITE_MODE') OR define('FILE_WRITE_MODE', 0666);
defined('DIR_READ_MODE')   OR define('DIR_READ_MODE', 0755);
defined('DIR_WRITE_MODE')  OR define('DIR_WRITE_MODE', 0755);

/*
|--------------------------------------------------------------------------
| File Stream Modes
|--------------------------------------------------------------------------
|
| These modes are used when working with fopen()/popen()
|
*/
defined('FOPEN_READ')                           OR define('FOPEN_READ', 'rb');
defined('FOPEN_READ_WRITE')                     OR define('FOPEN_READ_WRITE', 'r+b');
defined('FOPEN_WRITE_CREATE_DESTRUCTIVE')       OR define('FOPEN_WRITE_CREATE_DESTRUCTIVE', 'wb'); // truncates existing file data, use with care
defined('FOPEN_READ_WRITE_CREATE_DESCTRUCTIVE') OR define('FOPEN_READ_WRITE_CREATE_DESTRUCTIVE', 'w+b'); // truncates existing file data, use with care
defined('FOPEN_WRITE_CREATE')                   OR define('FOPEN_WRITE_CREATE', 'ab');
defined('FOPEN_READ_WRITE_CREATE')              OR define('FOPEN_READ_WRITE_CREATE', 'a+b');
defined('FOPEN_WRITE_CREATE_STRICT')            OR define('FOPEN_WRITE_CREATE_STRICT', 'xb');
defined('FOPEN_READ_WRITE_CREATE_STRICT')       OR define('FOPEN_READ_WRITE_CREATE_STRICT', 'x+b');

/*
|--------------------------------------------------------------------------
| Exit Status Codes
|--------------------------------------------------------------------------
|
| Used to indicate the conditions under which the script is exit()ing.
| While there is no universal standard for error codes, there are some
| broad conventions.  Three such conventions are mentioned below, for
| those who wish to make use of them.  The CodeIgniter defaults were
| chosen for the least overlap with these conventions, while still
| leaving room for others to be defined in future versions and user
| applications.
|
| The three main conventions used for determining exit status codes
| are as follows:
|
|    Standard C/C++ Library (stdlibc):
|       http://www.gnu.org/software/libc/manual/html_node/Exit-Status.html
|       (This link also contains other GNU-specific conventions)
|    BSD sysexits.h:
|       http://www.gsp.com/cgi-bin/man.cgi?section=3&topic=sysexits
|    Bash scripting:
|       http://tldp.org/LDP/abs/html/exitcodes.html
|
*/
defined('EXIT_SUCCESS')        OR define('EXIT_SUCCESS', 0); // no errors
defined('EXIT_ERROR')          OR define('EXIT_ERROR', 1); // generic error
defined('EXIT_CONFIG')         OR define('EXIT_CONFIG', 3); // configuration error
defined('EXIT_UNKNOWN_FILE')   OR define('EXIT_UNKNOWN_FILE', 4); // file not found
defined('EXIT_UNKNOWN_CLASS')  OR define('EXIT_UNKNOWN_CLASS', 5); // unknown class
defined('EXIT_UNKNOWN_METHOD') OR define('EXIT_UNKNOWN_METHOD', 6); // unknown class member
defined('EXIT_USER_INPUT')     OR define('EXIT_USER_INPUT', 7); // invalid user input
defined('EXIT_DATABASE')       OR define('EXIT_DATABASE', 8); // database error
defined('EXIT__AUTO_MIN')      OR define('EXIT__AUTO_MIN', 9); // lowest automatically-assigned error code
defined('EXIT__AUTO_MAX')      OR define('EXIT__AUTO_MAX', 125); // highest automatically-assigned error code



/*
|--------------------------------------------------------------------------
| CUSTOM LATTES CONSTANTS
|--------------------------------------------------------------------------
| DESCRICAO : Parte separada especificamente para utilizacao de constantes 
| da aplicacao LattesTimeline. Foi utilizado o metodo padrao do PHP 
| "define", para definir a chave e o valor das constantes.
|--------------------------------------------------------------------------
*/
/*
 * Constante de utilizacao para a permissao da pasta de upload dos arquivos 
 * XML's.
*/
define('LATTES_DIR_CHMOD', 0777);

/*
 * Constantes que sao utilizadas para realizar a QUERY de busca de um NODE 
 * especifico contido dentro do arquivo XML, atraves do metodo XPATH.
 * 
 * OBS : Constantes comecadas com "Q_" sao consultas de NODE's e comecadas
 * por "QA_" sao consultas de atributos dentro dos NODE's.
*/
define('Q_INTEGRANTES_PROJETO',								'./PROJETO-DE-PESQUISA/EQUIPE-DO-PROJETO/INTEGRANTES-DO-PROJETO');
define('Q_FINANCIADORES_PROJETO',							'./PROJETO-DE-PESQUISA/FINANCIADORES-DO-PROJETO');
define('Q_ORIENTACOES_ANDAMENTO_INICIACAO', 				'/CURRICULO-VITAE/DADOS-COMPLEMENTARES/ORIENTACOES-EM-ANDAMENTO/ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA');
define('Q_ORIENTACOES_ANDAMENTO_MESTRADO', 					'/CURRICULO-VITAE/DADOS-COMPLEMENTARES/ORIENTACOES-EM-ANDAMENTO/ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO');
define('Q_ORIENTACOES_CONCLUIDAS_MESTRADO', 				'/CURRICULO-VITAE/OUTRA-PRODUCAO/ORIENTACOES-CONCLUIDAS/ORIENTACOES-CONCLUIDAS-PARA-MESTRADO');
define('Q_ORIENTACOES_CONCLUIDAS_OUTRAS',					'/CURRICULO-VITAE/OUTRA-PRODUCAO/ORIENTACOES-CONCLUIDAS/OUTRAS-ORIENTACOES-CONCLUIDAS');
define('Q_PARTICIPACAO_EM_BANCA_DE_GRADUACAO', 				'/CURRICULO-VITAE/DADOS-COMPLEMENTARES/PARTICIPACAO-EM-BANCA-TRABALHOS-CONCLUSAO/PARTICIPACAO-EM-BANCA-DE-GRADUACAO');
define('Q_PARTICIPACAO_EM_BANCA_DE_ESPECIALIZACAO', 		'/CURRICULO-VITAE/DADOS-COMPLEMENTARES/PARTICIPACAO-EM-BANCA-TRABALHOS-CONCLUSAO/PARTICIPACAO-EM-BANCA-DE-APERFEICOAMENTO-ESPECIALIZACAO');
define('Q_PARTICIPACAO_EM_BANCA_DE_MESTRADO', 				'/CURRICULO-VITAE/DADOS-COMPLEMENTARES/PARTICIPACAO-EM-BANCA-TRABALHOS-CONCLUSAO/PARTICIPACAO-EM-BANCA-DE-MESTRADO');
define('Q_PARTICIPACAO_EM_BANCA_DE_QUALIFICACAO', 			'/CURRICULO-VITAE/DADOS-COMPLEMENTARES/PARTICIPACAO-EM-BANCA-TRABALHOS-CONCLUSAO/PARTICIPACAO-EM-BANCA-DE-EXAME-QUALIFICACAO');
define('Q_PARTICIPACAO_EM_PROJETO', 						'/CURRICULO-VITAE/DADOS-GERAIS/ATUACOES-PROFISSIONAIS/ATUACAO-PROFISSIONAL/ATIVIDADES-DE-PARTICIPACAO-EM-PROJETO/PARTICIPACAO-EM-PROJETO');
define('QA_PARTICIPANTES_BANCA',							'./PARTICIPANTE-BANCA/@NOME-PARA-CITACAO-DO-PARTICIPANTE-DA-BANCA');
define('Q_PRODUCAO_BIBLIOGRAFICA_CAPITULOS', 				'/CURRICULO-VITAE/PRODUCAO-BIBLIOGRAFICA/LIVROS-E-CAPITULOS/CAPITULOS-DE-LIVROS-PUBLICADOS/CAPITULO-DE-LIVRO-PUBLICADO');
define('Q_PRODUCAO_BIBLIOGRAFICA_EVENTOS', 					'/CURRICULO-VITAE/PRODUCAO-BIBLIOGRAFICA/TRABALHOS-EM-EVENTOS/TRABALHO-EM-EVENTOS');
define('Q_PRODUCAO_BIBLIOGRAFICA_LIVROS', 					'/CURRICULO-VITAE/PRODUCAO-BIBLIOGRAFICA/LIVROS-E-CAPITULOS/LIVROS-PUBLICADOS-OU-ORGANIZADOS/LIVRO-PUBLICADO-OU-ORGANIZADO');
define('Q_PRODUCAO_BIBLIOGRAFICA_OUTRAS_PRODUCOES', 		'/CURRICULO-VITAE/PRODUCAO-BIBLIOGRAFICA/DEMAIS-TIPOS-DE-PRODUCAO-BIBLIOGRAFICA/OUTRA-PRODUCAO-BIBLIOGRAFICA');
define('Q_PRODUCAO_TECNICA_TRABALHO_TECNICO', 				'/CURRICULO-VITAE/PRODUCAO-TECNICA/TRABALHO-TECNICO');

/*
 * Constantes de utilização específica para consulta de atributos 
 * dos nós.
*/
define('QA_ANO_DE_FIM_PROJETO',								'./PROJETO-DE-PESQUISA/@ANO-FIM');
define('QA_ANO_DE_INICIO_GRADUACAO', 						'/CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/GRADUACAO/@ANO-DE-INICIO');
define('QA_ANO_DE_INICIO_PROJETO',							'./PROJETO-DE-PESQUISA/@ANO-INICIO');
define('QA_ANO_GRADUACAO',									'./DADOS-BASICOS-DA-PARTICIPACAO-EM-BANCA-DE-GRADUACAO/@ANO');
define('QA_ANO_ESPECIALIZACAO',			 					'./DADOS-BASICOS-DA-PARTICIPACAO-EM-BANCA-DE-APERFEICOAMENTO-ESPECIALIZACAO/@ANO');
define('QA_ANO_MESTRADO',			 						'./DADOS-BASICOS-DA-PARTICIPACAO-EM-BANCA-DE-MESTRADO/@ANO');
define('QA_ANO_ORIENTACOES_CONCLUIDAS_MESTRADO',			'./DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO/@ANO');
define('QA_ANO_ORIENTACOES_CONCLUIDAS_OUTRAS', 				'./DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-CONCLUIDAS/@ANO');
define('QA_ANO_ORIENTACOES_EM_ANDAMENTO_MESTRADO',			'./DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@ANO');
define('QA_ANO_ORIENTACOES_EM_ANDAMENTO_INICIACAO',			'./DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA/@ANO');
define('QA_ANO_PRODUCOES_CAPITULO',	 						'./DADOS-BASICOS-DO-CAPITULO/@ANO');
define('QA_ANO_PRODUCOES_EVENTOS',	 						'./DADOS-BASICOS-DO-TRABALHO/@ANO-DO-TRABALHO');
define('QA_ANO_PRODUCOES_LIVRO',		 					'./DADOS-BASICOS-DO-LIVRO/@ANO');
define('QA_ANO_PRODUCOES_OUTRAS',	 						'./DADOS-BASICOS-DO-TRABALHO/@ANO-DO-TRABALHO');
define('QA_ANO_PRODUCOES_TECNICAS_TRABALHO',	 			'./DADOS-BASICOS-DO-TRABALHO-TECNICO/@ANO');
define('QA_ANO_QUALIFICACAO',		 						'./DADOS-BASICOS-DA-PARTICIPACAO-EM-BANCA-DE-EXAME-QUALIFICACAO/@ANO');
define('QA_BANCA_ESPECIALIZACAO_NOME_CANDIDATO', 			'./DETALHAMENTO-DA-PARTICIPACAO-EM-BANCA-DE-APERFEICOAMENTO-ESPECIALIZACAO/@NOME-DO-CANDIDATO');
define('QA_BANCA_ESPECIALIZACAO_NOME_CURSO', 				'./DETALHAMENTO-DA-PARTICIPACAO-EM-BANCA-DE-APERFEICOAMENTO-ESPECIALIZACAO/@NOME-CURSO');
define('QA_BANCA_ESPECIALIZACAO_NOME_INSTITUICAO', 			'./DETALHAMENTO-DA-PARTICIPACAO-EM-BANCA-DE-APERFEICOAMENTO-ESPECIALIZACAO/@NOME-INSTITUICAO');
define('QA_BANCA_ESPECIALIZACAO_TITULO', 					'./DADOS-BASICOS-DA-PARTICIPACAO-EM-BANCA-DE-APERFEICOAMENTO-ESPECIALIZACAO/@TITULO');
define('QA_BANCA_GRADUACAO_NOME_CANDIDATO', 				'./DETALHAMENTO-DA-PARTICIPACAO-EM-BANCA-DE-GRADUACAO/@NOME-DO-CANDIDATO');
define('QA_BANCA_GRADUACAO_NOME_CURSO', 					'./DETALHAMENTO-DA-PARTICIPACAO-EM-BANCA-DE-GRADUACAO/@NOME-CURSO');
define('QA_BANCA_GRADUACAO_NOME_INSTITUICAO', 				'./DETALHAMENTO-DA-PARTICIPACAO-EM-BANCA-DE-GRADUACAO/@NOME-INSTITUICAO');
define('QA_BANCA_GRADUACAO_TITULO', 						'./DADOS-BASICOS-DA-PARTICIPACAO-EM-BANCA-DE-GRADUACAO/@TITULO');
define('QA_BANCA_MESTRADO_ANO', 							'./DADOS-BASICOS-DA-PARTICIPACAO-EM-BANCA-DE-MESTRADO/@ANO');
define('QA_BANCA_MESTRADO_NOME_CANDIDATO', 					'./DETALHAMENTO-DA-PARTICIPACAO-EM-BANCA-DE-MESTRADO/@NOME-DO-CANDIDATO');
define('QA_BANCA_MESTRADO_NOME_CURSO', 						'./DETALHAMENTO-DA-PARTICIPACAO-EM-BANCA-DE-MESTRADO/@NOME-CURSO');
define('QA_BANCA_MESTRADO_NOME_INSTITUICAO', 				'./DETALHAMENTO-DA-PARTICIPACAO-EM-BANCA-DE-MESTRADO/@NOME-INSTITUICAO');
define('QA_BANCA_MESTRADO_TITULO', 							'./DADOS-BASICOS-DA-PARTICIPACAO-EM-BANCA-DE-MESTRADO/@TITULO');
define('QA_BANCA_QUALI_NOME_CANDIDATO', 					'./DETALHAMENTO-DA-PARTICIPACAO-EM-BANCA-DE-EXAME-QUALIFICACAO/@NOME-DO-CANDIDATO');
define('QA_BANCA_QUALI_NOME_CURSO', 						'./DETALHAMENTO-DA-PARTICIPACAO-EM-BANCA-DE-EXAME-QUALIFICACAO/@NOME-CURSO');
define('QA_BANCA_QUALI_NOME_INSTITUICAO', 					'./DETALHAMENTO-DA-PARTICIPACAO-EM-BANCA-DE-EXAME-QUALIFICACAO/@NOME-INSTITUICAO');
define('QA_BANCA_QUALI_TITULO', 							'./DADOS-BASICOS-DA-PARTICIPACAO-EM-BANCA-DE-EXAME-QUALIFICACAO/@TITULO');
define('QA_NOME_COMPLETO',		 							'/CURRICULO-VITAE/DADOS-GERAIS/@NOME-COMPLETO');
define('QA_ORIENT_CONCLUIDA_MESTRADO_NOME_CURSO',			'./DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO/@NOME-DO-CURSO');
define('QA_ORIENT_CONCLUIDA_MESTRADO_NOME_INSTITUICAO',		'./DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO/@NOME-DA-INSTITUICAO');
define('QA_ORIENT_CONCLUIDA_MESTRADO_NOME_ORIENTADO',		'./DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO/@NOME-DO-ORIENTADO');
define('QA_ORIENT_CONCLUIDA_MESTRADO_TITULO',				'./DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO/@TITULO');
define('QA_ORIENT_CONCLUIDA_OUTRA_NOME_CURSO',				'./DETALHAMENTO-DE-OUTRAS-ORIENTACOES-CONCLUIDAS/@NOME-DO-CURSO');
define('QA_ORIENT_CONCLUIDA_OUTRA_NOME_INSTITUICAO',		'./DETALHAMENTO-DE-OUTRAS-ORIENTACOES-CONCLUIDAS/@NOME-DA-INSTITUICAO');
define('QA_ORIENT_CONCLUIDA_OUTRA_NOME_ORIENTADO',			'./DETALHAMENTO-DE-OUTRAS-ORIENTACOES-CONCLUIDAS/@NOME-DO-ORIENTADO');
define('QA_ORIENT_CONCLUIDA_OUTRA_TITULO',					'./DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-CONCLUIDAS/@TITULO');
define('QA_ORIENT_ANDAMENTO_INICIACAO_NOME_CURSO',			'./DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA/@NOME-CURSO');
define('QA_ORIENT_ANDAMENTO_INICIACAO_NOME_INSTITUICAO',	'./DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA/@NOME-INSTITUICAO');
define('QA_ORIENT_ANDAMENTO_INICIACAO_NOME_ORIENTADO',		'./DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA/@NOME-DO-ORIENTADO');
define('QA_ORIENT_ANDAMENTO_INICIACAO_TITULO',				'./DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA/@TITULO-DO-TRABALHO');
define('QA_ORIENT_ANDAMENTO_MESTRADO_NOME_CURSO',			'./DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@NOME-CURSO');
define('QA_ORIENT_ANDAMENTO_MESTRADO_NOME_INSTITUICAO',		'./DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@NOME-INSTITUICAO');
define('QA_ORIENT_ANDAMENTO_MESTRADO_NOME_ORIENTADO',		'./DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@NOME-DO-ORIENTANDO');
define('QA_ORIENT_ANDAMENTO_MESTRADO_TITULO',				'./DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@TITULO-DO-TRABALHO');
define('QA_OUTRA_PRODUCAO_ANO',								'./DADOS-BASICOS-DE-OUTRA-PRODUCAO/@ANO');
define('QA_OUTRA_PRODUCAO_NATUREZA',						'./DADOS-BASICOS-DE-OUTRA-PRODUCAO/@NATUREZA');
define('QA_OUTRA_PRODUCAO_TITULO',							'./DADOS-BASICOS-DE-OUTRA-PRODUCAO/@TITULO');
define('Q_PRODUCAO_AUTORES',								'./AUTORES');
define('QA_PRODUCAO_CAPITULO_ANO',							'./DADOS-BASICOS-DO-CAPITULO/@ANO');
define('QA_PRODUCAO_CAPITULO_EDICAO_REVISAO',				'./DETALHAMENTO-DO-CAPITULO/@NUMERO-DA-EDICAO-REVISAO');
define('QA_PRODUCAO_CAPITULO_PAG_FINAL',					'./DETALHAMENTO-DO-CAPITULO/@PAGINA-FINAL');
define('QA_PRODUCAO_CAPITULO_PAG_INICIAL',					'./DETALHAMENTO-DO-CAPITULO/@PAGINA-INICIAL');
define('QA_PRODUCAO_CAPITULO_TITULO',						'./DADOS-BASICOS-DO-CAPITULO/@TITULO-DO-CAPITULO-DO-LIVRO');
define('QA_PRODUCAO_CAPITULO_TITULO_LIVRO',					'./DETALHAMENTO-DO-CAPITULO/@TITULO-DO-LIVRO');
define('QA_PRODUCAO_CAPITULO_VOLUMES',						'./DETALHAMENTO-DO-CAPITULO/@NUMERO-DE-VOLUMES');
define('QA_PRODUCAO_EM_EVENTO_ANO_TRABALHO',				'./DADOS-BASICOS-DO-TRABALHO/@ANO-DO-TRABALHO');
define('QA_PRODUCAO_EM_EVENTO_CIDADE_EVENTO',				'./DETALHAMENTO-DO-TRABALHO/@CIDADE-DO-EVENTO');
define('QA_PRODUCAO_EM_EVENTO_NOME_EVENTO',					'./DETALHAMENTO-DO-TRABALHO/@NOME-DO-EVENTO');
define('QA_PRODUCAO_EM_EVENTO_TITULO_EVENTO',				'./DETALHAMENTO-DO-TRABALHO/@TITULO-DOS-ANAIS-OU-PROCEEDINGS');
define('QA_PRODUCAO_EM_EVENTO_TITULO_TRABALHO',				'./DADOS-BASICOS-DO-TRABALHO/@TITULO-DO-TRABALHO');
define('QA_PRODUCAO_LIVRO_ANO',								'./DADOS-BASICOS-DO-LIVRO/@ANO');
define('QA_PRODUCAO_LIVRO_NUMERO_EDICAO_REVISAO',			'./DETALHAMENTO-DO-LIVRO/@NUMERO-DA-EDICAO-REVISAO');
define('QA_PRODUCAO_LIVRO_NUMERO_VOLUMES',					'./DETALHAMENTO-DO-LIVRO/@NUMERO-DE-VOLUMES');
define('QA_PRODUCAO_LIVRO_TITULO',							'./DADOS-BASICOS-DO-LIVRO/@TITULO-DO-LIVRO');
define('QA_PRODUCAO_TECNICO_ANO',							'./DADOS-BASICOS-DO-TRABALHO-TECNICO/@ANO');
define('QA_PRODUCAO_TECNICO_TITULO',						'./DADOS-BASICOS-DO-TRABALHO-TECNICO/@TITULO-DO-TRABALHO-TECNICO');
define('QA_PROJETO_DESCRICAO',								'./PROJETO-DE-PESQUISA/@DESCRICAO-DO-PROJETO');
define('QA_PROJETO_NATUREZA',								'./PROJETO-DE-PESQUISA/@NATUREZA');
define('QA_PROJETO_NOME',		 							'./PROJETO-DE-PESQUISA/@NOME-DO-PROJETO');
define('QA_PROJETO_NUM_DOUTORADO',							'./PROJETO-DE-PESQUISA/@NUMERO-DOUTORADO');
define('QA_PROJETO_NUM_ESPECIALIZACAO',						'./PROJETO-DE-PESQUISA/@NUMERO-ESPECIALIZACAO');
define('QA_PROJETO_NUM_GRADUACAO',							'./PROJETO-DE-PESQUISA/@NUMERO-GRADUACAO');
define('QA_PROJETO_NUM_MESTRADO_ACADEMICO',					'./PROJETO-DE-PESQUISA/@NUMERO-MESTRADO-ACADEMICO');
define('QA_PROJETO_NUM_MESTRADO_PROF',						'./PROJETO-DE-PESQUISA/@NUMERO-MESTRADO-PROF');
define('QA_PROJETO_SITUACAO',								'./PROJETO-DE-PESQUISA/@SITUACAO');

/*
 * Constantes definidas apenas para recuperar o valor dos atributos 
 * consultados dentro dos NODE's. Uma vez feita a consulta, para 
 * retornar o valor eh necessario acessa-lo atraves de indice de 
 * array como STRING.
*/
define('LABEL_ANO', 										'ANO');
define('LABEL_ANO_DO_TRABALHO', 							'ANO-DO-TRABALHO');
define('LABEL_ANO_FIM',										'ANO-FIM');
define('LABEL_ANO_INICIO',									'ANO-INICIO');
define('LABEL_CIDADE_DO_EVENTO',							'CIDADE-DO-EVENTO');
define('LABEL_DESCRICAO_PROJETO',							'DESCRICAO-DO-PROJETO');
define('LABEL_NATUREZA',									'NATUREZA');
define('LABEL_NOME_COMPLETO',								'NOME-COMPLETO');
define('LABEL_NOME_CURSO',									'NOME-CURSO');
define('LABEL_NOME_DA_INSTITUICAO',							'NOME-DA-INSTITUICAO');
define('LABEL_NOME_DO_CANDIDATO',							'NOME-DO-CANDIDATO');
define('LABEL_NOME_DO_CURSO',								'NOME-DO-CURSO');
define('LABEL_NOME_DO_EVENTO', 								'NOME-DO-EVENTO');
define('LABEL_NOME_DO_ORIENTADO', 							'NOME-DO-ORIENTADO');
define('LABEL_NOME_DO_ORIENTANDO', 							'NOME-DO-ORIENTANDO');
define('LABEL_NOME_DO_PROJETO', 							'NOME-DO-PROJETO');
define('LABEL_NOME_INSTITUICAO',							'NOME-INSTITUICAO');
define('LABEL_NOME_PARA_CITACAO',							'NOME-PARA-CITACAO');
define('LABEL_NOME_PARA_CITACAO_PARCIPANTE',				'NOME-PARA-CITACAO-DO-PARTICIPANTE-DA-BANCA');
define('LABEL_NUMERO_EDICAO_REVISAO', 						'NUMERO-DA-EDICAO-REVISAO');
define('LABEL_NUMERO_ESPECIALIZACAO', 						'NUMERO-ESPECIALIZACAO');
define('LABEL_NUMERO_DOUTORADO', 							'NUMERO-DOUTORADO');
define('LABEL_NUMERO_GRADUACAO', 							'NUMERO-GRADUACAO');
define('LABEL_NUMERO_MESTRADO_ACADEMICO', 					'NUMERO-MESTRADO-ACADEMICO');
define('LABEL_NUMERO_MESTRADO_PROF', 						'NUMERO-MESTRADO-PROF');
define('LABEL_NUMERO_VOLUMES',	 							'NUMERO-DE-VOLUMES');
define('LABEL_PAGINA_FINAL', 								'PAGINA-FINAL');
define('LABEL_PAGINA_INICIAL', 								'PAGINA-INICIAL');
define('LABEL_RESPONSAVEL', 								'FLAG-RESPONSAVEL');
define('LABEL_SITUACAO', 									'SITUACAO');
define('LABEL_TITULO', 										'TITULO');
define('LABEL_TITULO_DO_CAPITULO_DO_LIVRO', 				'TITULO-DO-CAPITULO-DO-LIVRO');
define('LABEL_TITULO_DO_EVENTO', 							'TITULO-DOS-ANAIS-OU-PROCEEDINGS');
define('LABEL_TITULO_DO_LIVRO', 							'TITULO-DO-LIVRO');
define('LABEL_TITULO_DO_TRABALHO', 							'TITULO-DO-TRABALHO');
define('LABEL_TITULO_DO_TRABALHO_TECNICO', 					'TITULO-DO-TRABALHO-TECNICO');

/*
 * Constantes definidas para comparacao de valores padroes dos 
 * atributos do arquivo XML.
*/
define('VALUE_FLAG_RESPONSAVEL_NEGATIVO', 					'NAO');
define('VALUE_SITUACAO_PROJETO_ANDAMENTO', 					'EM_ANDAMENTO');
